### PR TITLE
Add annotations which scope over a part of a doc

### PR DESCRIPTION
**Pull request by nwf**
A first pass at #10

### CODE REVIEW

**Comment by david-christiansen** [comment]
I would expect to have something like

```
-- | Display a rendered document.
--
-- This function takes a means of starting an annotated region, a means of ending it,
-- and a means of displaying a string, with effects to display or compute the output.
-- The Ints are the string indexes of the start and end points of annotated regions.
displayDecorated :: (Applicative f, Monoid o)
                 => (Int -> a -> f o) -- ^ How to start an annotated region
                 -> (Int -> a -> f o) -- ^ How to end an annotated region
                 -> (String -> f o)
                 -> SimpleDoc a
                 -> f o
```
which allows general rendering of documents and their annotations. For example, colored output on Windows would let `f` be `IO` and `o` be `()`. Colored output on Unix would let `f` be `Id` and `o` be `String`, with start/end actions that compute ANSI codes. Using `State [List (a, Int)]` for `f` and an accumulator of strings and offset-length-annotation triples as `o` lets you render the document to a string and out-of-band annotations for editor support. Others are also possible!

**Comment by nwf** [comment]
I don't understand the purpose of the `Int`s.  That said, new draft incoming. :)

**Comment by nwf** [comment]
Pinging @david-christiansen.  Is this sufficient to replace annotated-wl-pprint for you or is there yet something missing?

**Comment by david-christiansen** [comment]
@nwf  Sorry I didn't see your reply before!
 
The Ints are there to enable out-of-band signalling of annotation information. In Idris, we do two things with annotated pretty-printer documents:
 1. Render them directly with colors, which must be inside `IO` to support Windows
 2. Render them to a pair of a string and a list of a-length-annotation triples, so that Emacs and Atom can give much richer displays than the console colors

So it looks like that is still missing two things to work in Idris:
 1. A way to map over annotations (the `Functor` instance in annotated-wl-pprint)
 2. A way to do out-of-band signalling of annotations

Thanks!

**Comment by nwf** [comment]
1 is pretty easy to add; it's just:

```
fmapAnn :: (a -> a') -> Doc a e -> Doc a' e
fmapAnn f = docLeafyRec Effect (Annotate . f)
```

I can do that easily enough with another pull request.  But, I don't think I understand what you mean by 2... is something like this (which I believe can be done entirely through the exported API, except that I didn't add `displayDecorated` to the not-Internal module... sigh.  Also in the next PR.) not sufficient?

```
{-# LANGUAGE TemplateHaskell #-}

import Control.Lens
import Data.Monoid
import Text.PrettyPrint.Free.Internal

data St a = St {
  _st_len :: Int,
  _st_pend :: [(Int,a)],
  _st_res :: [(Int,Int,a)],
  _st_str :: String -> String
}
$(makeLenses ''St)

pe :: Applicative f => (a -> a) -> f (Endo a)
pe = pure . Endo

push, pop :: Applicative f => a -> f (Endo (St a))
push a = pe (\st -> (st_pend %~ ((st ^. st_len, a):)) st)
pop  _ = pe (\(St l p r s) -> case p of
                                  [] -> error "Malformed document"
                                  ((pi,pa):ps) -> St l ps ((pi,l,pa):r) s)
str  x = pe (\(St l p r s) -> St (l + length x) p r ((++x) . s))

oobdisp = displayDecorated push pop (\_ -> pe id) str
```

or perhaps the more overtly stateful

```
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE FlexibleContexts #-}

import Control.Lens
import Control.Monad.State
import Text.PrettyPrint.Free.Internal

data St a = St {
  _st_len :: Int,
  _st_pend :: [(Int,a)],
  _st_res :: [(Int,Int,a)]
}
$(makeLenses ''St)

push :: (Monad m) => a -> StateT (St a) m String
push a = modify (\st -> (st_pend %~ ((_st_len st, a):)) st) >> pure mempty
pop  _ = modify (\(St l p r) -> case p of
                                  [] -> error "Malformed document"
                                  ((pi,pa):ps) -> St l ps ((pi,l,pa):r))
         >> pure mempty
str  x = modify (st_len %~ (+ length x)) >> pure x

oobdisp :: (Monad m) => SimpleDoc a e -> m (String, St a)
oobdisp = flip runStateT (St 0 [] []) . displayDecorated push pop (\_ -> pure "") str
```

**Comment by nwf** [comment]
Ack; forgot to tag @david-christiansen just in case.

**Comment by david-christiansen** [comment]
It is quite likely that this does we need - I'd really need to bust out the giant table of lens operators and squint for 45 minutes to be sure ;-)  If so, then we're good to go, and once my PhD is handed in then I'll look into porting everything and see what happens!

Thanks so much for doing this, @nwf!

**Comment by david-christiansen** [comment]
What about mapping the point effects to something annotated? That doesn't seem immediately possible with `displayDecorated` as written.

**Comment by david-christiansen** [comment]
Scratch that, I'm not thinking imperatively enough - of course they can be :)

**Comment by ekmett** [comment]
Easier still would just be adding a Bifunctor instance.

**Pull request merged**
